### ISSUE TITLE
is_mobile? not working

### ISSUE THREAD

**Issue by austinthecoder** [kevinelliott/agent_orange#1]
ua.device is returning 'Mobile' but ua.is_mobile? is returning false

Does this gem have tests?

**Comment by kevinelliott** [comment]
Resolved. I'll create an issue separately to track the gem tests. There are no tests now, but I have been planning to create them (as mentioned on the main github page for this gem under Status).

**Comment by austinthecoder** [comment]
Oops, missed that section. You'll definitely more traction on this gem with tests. Good luck!

**Comment by kevinelliott** [comment]
Thanks, yep I agree. Didn't expect any traction yet to begin with, but it will encourage me to get full coverage much more quickly.
