### ISSUE TITLE
Chrome on Mac is identified as Safari

### ISSUE THREAD

**Issue by cw-moshe** [kevinelliott/agent_orange#15]
For this user agent:
5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.165 Safari/535.19

It is identified as Safari when doing:
device.engine.browser.to_s

**Comment by cw-moshe** [comment]
Never mind. Getting the gem directly from git solves it. I guess the gem is outdated.

**Comment by kevinelliott** [comment]
There are some changes that were committed recently that should resolve this one, though I will have to take a look and confirm. They have not yet been pushed out to a new gem version, but are in the repository if you wish to use the latest and see if it catches this.

**Comment by cw-moshe** [comment]
Yeah, see above, it's fixed

**Comment by kevinelliott** [comment]
Oh, I see now. I was responding from email. Thanks!

I'll push out a new gem version today.
