### ISSUE TITLE
Spec 'checking with real browsers list should parse browsers from list' failure

### ISSUE THREAD

**Issue by kevinelliott** [kevinelliott/agent_orange#25]
1) AgentOrange::UserAgent checking with real browsers list should parse browsers from list
     Failure/Error: params[:browser_names].should include(br_name)
       expected ["Opera"] to include "MSIE"
     # ./spec/long_user_agent_spec.rb:50:in `block (5 levels) in <top (required)>'
     # ./spec/long_user_agent_spec.rb:46:in`each'
     # ./spec/long_user_agent_spec.rb:46:in `block (4 levels) in <top (required)>'
     # ./spec/long_user_agent_spec.rb:21:in`each'
     # ./spec/long_user_agent_spec.rb:21:in `block (3 levels) in <top (required)>'

**Comment by kevinelliott** [comment]
@brain-geek Any chance you can take a look at this?

**Comment by brain-geek** [comment]
Hello, Kevin.

As I see, agent orange works right. It detects 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1' user-agent as IE, not opera.

Pull request: #27 .

**Comment by kevinelliott** [comment]
The PR submitted resolves the test failure correctly. Merged.
