### ISSUE TITLE
gemspec doesn't work with bundler

### ISSUE THREAD

**Issue by joshuasiler** [kevinelliott/agent_orange#7]
When using Rails and bundler, the gemspec is flagged as invalid by bundler, and gem installation fails, when using git as a source.

For example, this line in my gemspec was failing with a bundler error "invalid gemspec": 

```
gem 'agent_orange', '0.1.0', :git => 'git://github.com/eatenbyagrue/agent_orange.git', :branch => 'hiringthing'
```

I fixed in a branch of my fork with the following change to the gemspec.

```
s.files         = "agent_orange-0.1.0.gem"
```

**Comment by joshuasiler** [comment]
Hmmm still having problems. Bundler installs the first time, then fails the second time. Have you seen this issue at all?

**Comment by joshuasiler** [comment]
Ended up with this in my gemspec to get it to work.

```
require 'rake'
s.files = FileList['lib/**/*.rb', 'bin/*', '[A-Z]*', 'test/**/*'].to_a
```

**Comment by kevinelliott** [comment]
This is isolated to your fork, as the original gemspec was generated by bundler and only modified slightly.
